openapi: 3.1.0
info:
  title: 人事系统
  description: ''
  version: 1.0.0
tags:
  - name: 人事-rs
paths:
  /v1/rs/list_jzg:
    get:
      summary: 教职工列表查询
      deprecated: false
      description: 教职工列表查询
      tags:
        - 人事-rs
      parameters:
        - name: dep
          in: query
          description: 单位
          required: false
          example: ''
          schema:
            type: string
        - name: dqztdm
          in: query
          description: 当前状态代码
          required: false
          schema:
            type: string
        - name: yrfsdm
          in: query
          description: 用人方式代码
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  XM:
                    type: string
                    title: 姓名
                  ZGH:
                    type: string
                    title: 职工号
                required:
                  - XM
                  - ZGH
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - XM: XM
                        ZGH: ZGH
                      - XM: XM
                        ZGH: ZGH
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/lis_xpxg:
    get:
      summary: 获取校聘校管人员列表
      deprecated: false
      description: 获取校聘校管人员列表
      tags:
        - 人事-rs
      parameters:
        - name: dep
          in: query
          description: 单位
          required: false
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  XM:
                    type: string
                    title: 姓名
                  DEP:
                    type: string
                    title: 单位
                  DQZTDM:
                    type: string
                    title: 当前状态代码
                  ZGH:
                    type: string
                    title: 职工号
                  YRFSDM:
                    type: string
                    title: 用人方式代码
                required:
                  - XM
                  - DEP
                  - DQZTDM
                  - ZGH
                  - YRFSDM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - XM: ''
                        DEP: '2012'
                        DQZTDM: '22'
                        ZGH: ''
                        YRFSDM: '101'
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/detail_jzg:
    get:
      summary: 教职工详情查询
      deprecated: false
      description: 教职工详情查询
      tags:
        - 人事-rs
      parameters:
        - name: zgh
          in: query
          description: 职工号
          required: false
          example:
            - '20234011'
            - '20150047'
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  YXDM:
                    type: string
                    title: 院系代码
                  MZDM:
                    type: string
                    title: 民族代码
                  XM:
                    type: string
                    title: 姓名
                  ZZMMDM:
                    type: string
                    title: 政治面貌代码
                  DQZTDM:
                    type: string
                    title: 当前状态代码
                  ZGH:
                    type: string
                    title: 职工号
                  YRFSDM:
                    type: string
                    title: 用人方式代码
                  ZGXLDM:
                    type: string
                    title: 最高学历代码
                  ZYJSZWJBDM:
                    type: string
                    title: 专业技术职务级别代码
                required:
                  - YXDM
                  - MZDM
                  - XM
                  - ZZMMDM
                  - DQZTDM
                  - ZGH
                  - YRFSDM
                  - ZGXLDM
                  - ZYJSZWJBDM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - YXDM: YXDM
                        MZDM: MZDM
                        XM: XM
                        ZZMMDM: ZZMMDM
                        DQZTDM: DQZTDM
                        ZGH: ZGH
                        YRFSDM: YRFSDM
                        ZGXLDM: ZGXLDM
                        ZYJSZWJBDM: ZYJSZWJBDM
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/dm_mzdm:
    get:
      summary: 人事系统民族代码
      deprecated: false
      description: 人事系统民族代码
      tags:
        - 人事-rs
      parameters:
        - name: dm
          in: query
          description: 民族代码
          required: false
          example: '33'
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MC:
                    type: string
                    title: 名称
                  DM:
                    type: string
                    title: 代码
                required:
                  - MC
                  - DM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - MC: 羌族
                        DM: '33'
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/dm_zzmmdm:
    get:
      summary: 人事系统政治面貌代码
      deprecated: false
      description: 人事系统政治面貌代码
      tags:
        - 人事-rs
      parameters:
        - name: dm
          in: query
          description: 政治面貌代码
          required: false
          example: '13'
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MC:
                    type: string
                    title: 名称
                  DM:
                    type: string
                    title: 代码
                required:
                  - MC
                  - DM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - MC: 群众
                        DM: '13'
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/dm_yxdm:
    get:
      summary: 人事系统组织机构代码
      deprecated: false
      description: 人事系统组织机构代码
      tags:
        - 人事-rs
      parameters:
        - name: dm
          in: query
          description: 院系代码
          required: false
          example: '1001'
          schema:
            type: string
        - name: Authorization
          in: header
          description: ''
          required: true
          example: >-
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJlZTI1OTMwYzk0NjI0YTU3ZmY1NzMwNzQ3YTUyZjc4NCIsImV4cCI6MTcxODc4NDYxM30.A0V-f99nss18twxOFdBTd1rkyVmoqpUN0HhIJ3cj_SI
          schema:
            type: string
        - name: Content-Type
          in: header
          description: ''
          required: false
          example: application/x-www-form-urlencoded
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MC:
                    type: string
                    title: 代码
                  DM:
                    type: string
                    title: 名称
                required:
                  - MC
                  - DM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - MC: 党政办公室
                        DM: '1001'
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/dm_dqztdm:
    get:
      summary: 人事教职工当前状态代码
      deprecated: false
      description: 人事教职工当前状态代码
      tags:
        - 人事-rs
      parameters:
        - name: dm
          in: query
          description: 当前状态代码
          required: false
          example: '01'
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MC:
                    type: string
                    title: 代码
                  DM:
                    type: string
                    title: 名称
                required:
                  - MC
                  - DM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - MC: 退休
                        DM: '01'
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/dm_yrfsdm:
    get:
      summary: 人事系统用人方式代码
      deprecated: false
      description: 人事系统用人方式代码
      tags:
        - 人事-rs
      parameters:
        - name: dm
          in: query
          description: 用人方式代码
          required: false
          example: '214'
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MC:
                    type: string
                    title: 代码
                  DM:
                    type: string
                    title: 名称
                required:
                  - MC
                  - DM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - MC: 事业编制
                        DM: '101'
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/dm_xldm:
    get:
      summary: 人事系统学历代码
      deprecated: false
      description: 人事系统学历代码
      tags:
        - 人事-rs
      parameters:
        - name: dm
          in: query
          description: 学历代码
          required: false
          example: '14'
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MC:
                    type: string
                    title: 名称
                  DM:
                    type: string
                    title: 代码
                required:
                  - MC
                  - DM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - MC: 硕士研究生毕业
                        DM: '14'
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
  /v1/rs/dm_gbzwjb:
    get:
      summary: 人事系统专业技术职务级别，党政职务代码
      deprecated: false
      description: 人事系统专业技术职务级别，党政职务代码
      tags:
        - 人事-rs
      parameters:
        - name: dm
          in: query
          description: 专业技术职务或党政职务代码
          required: false
          example: '121'
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  MC:
                    type: string
                    title: 名称
                  LS:
                    type: string
                    title: 类属
                  DM:
                    type: string
                    title: 代码
                required:
                  - MC
                  - LS
                  - DM
              examples:
                '1':
                  summary: 成功示例
                  value:
                    data:
                      - MC: 厅级正职
                        LS: '1'
                        DM: '121'
                    msg: null
                    success: true
      security:
        - apikey-header-Authorization: []
components:
  schemas: {}
  securitySchemes:
    apikey-header-Authorization:
      type: apiKey
      in: header
      name: Authorization
servers:
  - url: 'https://api.ynu.edu.cn'
    description: 服务地址
